Repository prgrms-web-devcourse-final-project/WEB5_6_OneTop_FE, pull requests merged in 2025-10, with the labels that each got.

#31 [FEAT]: 로그인상태 관리 업데이트 반영 api 연동
  src/app/api/actions/baseline.ts
  src/domains/baselines/api/clientBaselineApi.ts
  src/domains/baselines/components/BaselineContainer.tsx
  src/domains/baselines/components/BaselineView.tsx
  src/domains/baselines/stores/baselineStore.ts
  src/domains/baselines/types.ts
  src/share/hooks/useAuth.ts
  src/share/stores/authStore.ts
  src/share/utils/axios.ts
Labels: FEAT

#38 [FEAT]: 메인페이지 UI 작업
  public/comparison_left.png
  public/comparison_right.png
  public/feature_img.png
  public/hero_bg.png
  src/app/(main)/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/domains/main/components/Comparison.tsx
  src/domains/main/components/Feature.tsx
  src/domains/main/components/Guide.tsx
  src/domains/main/components/Hero.tsx
  src/domains/main/components/MainContainer.tsx
  src/domains/main/components/PinnedBackground.tsx
  src/domains/main/components/Statistics.tsx
  src/domains/scenarios/components/ScenarioContainer.tsx
Labels: FEAT

#40 [FIX]: 빌드 오류 수정
  src/domains/multiverse/hooks/useTreeLayout.ts
  src/share/components/Pagination.tsx
Labels: FIX

#46 [FIX]: 베이스라인 응답 변경에 따른 수정 및 url 주소 변경
  src/app/(protected)/scenario-list/page.tsx
  src/domains/scenario-list/api/getBaselineList.ts
  src/domains/scenario-list/component/BaselineSection.tsx
Labels: FIX

#53 [FEAT]: 메인 페이지 애니메이션 작업
  public/comparison_left.png
  public/parallel_universe01.png
  public/parallel_universe02.png
  public/quote_left.png
  public/quote_right.png
  src/domains/main/components/Feature.tsx
  src/domains/main/components/Guide.tsx
  src/domains/main/components/Hero.tsx
  src/domains/main/components/Statistics.tsx
Labels: FEAT

#59 [FIX]: 베이스라인 리스트 baseurl 수정
  src/domains/scenario-list/api/getBaselineList.ts
Labels: FIX

#63 [FIX]: 마이페이지 변경 및 베이스라인 삭제 구현
  public/404.png
  src/app/(protected)/scenario-list/page.tsx
  src/app/not-found.tsx
  src/domains/multiverse/components/ParticleBackground.tsx
  src/domains/multiverse/components/TreeFlow.tsx
  src/domains/multiverse/components/TreeFlowContent.tsx
  src/domains/my-page/components/Loading.tsx
  src/domains/my-page/components/MyPageContainer.tsx
  src/domains/my-page/components/mycomments/MyComments.tsx
  src/domains/my-page/components/myinfo/MyInfo.tsx
  src/domains/my-page/components/myinfo/MyInfoModal.tsx
  src/domains/my-page/components/myposts/MyPosts.tsx
  src/domains/my-page/components/myscenarios/MyScenarios.tsx
  src/domains/my-page/components/myusagestats/MyUsageStats.tsx
  src/domains/my-page/components/representativeprofile/RepresentativeProfile.tsx
  src/domains/my-page/components/representativeprofile/RepresentativeProfileModal.tsx
  src/domains/my-page/hooks/useMyInfo.ts
  src/domains/my-page/hooks/useRepresentativeProfile.ts
  src/domains/my-page/lib/schema.ts
  src/domains/scenario-list/api/BaselineApi.ts
  src/domains/scenario-list/component/Baseline.tsx
  src/domains/scenario-list/component/BaselineList.tsx
  src/domains/scenario-list/component/BaselineSection.tsx
  src/domains/scenario-list/component/DeleteBaselineButton.tsx
  src/domains/scenario-list/hooks/useBaselines.ts
  src/domains/scenario-list/types.ts
  src/share/components/ErrorToast.tsx
  src/share/components/Loading.tsx
  src/share/components/Modal.tsx
  src/share/components/Pagination.tsx
  src/share/config/queryKeys.ts
Labels: FEAT, FIX
